parameters:
    sidus_eav_model.entity.data.class: Sidus\EAVDemoBundle\Entity\Data
    sidus_eav_model.entity.value.class: Sidus\EAVDemoBundle\Entity\Value
    sidus_eav_model.manager.data.class: Sidus\EAVDemoBundle\Manager\DataManager

services:
    sidus_eav_model.manager.data:
        class: %sidus_eav_model.manager.data.class%
        arguments: [@doctrine.orm.entity_manager, @sidus_eav_model.doctrine.repository.data]
