sidus_eav_filter:
    configurations:
        project:
            entity: %sidus_eav_model.entity.data.class%
            sortable:
                - id
                - code
                - familyCode
                - createdAt
                - name
            fields:
                code:
                    attributes: [code]
                family: ~
                name:
                    attributes: [code]
                status:
                    attributes: [status]
                description:
                    attributes: [description, fullDescription]
                releaseDate:
                    type: date_range
                    attributes: [releaseDate]
#                associatedProjects:
#                    attributes: [associatedProjects]
#                tags:
#                    attributes: [tags]
