services:
    demo_eav_model.attribute_type.document:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments:
            - document
            - documentValue
            - sidus_resource
            - { resource_type: document }
        tags:
            - { name: sidus.attribute_type }

    demo_eav_model.attribute_type.image:
        class: '%sidus_eav_model.attribute_type.default.class%'
        arguments:
            - image
            - imageValue
            - demo_image
            - { resource_type: image }
        tags:
            - { name: sidus.attribute_type }
